title: 'Open Government Products - A Division of GovTech'
description: 'We build technology for the public good'
url: 'https://open.gov.sg'
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
collections:
    careers:
        output: true
    products:
        output: true
custom_css_path: /misc/custom.css
favicon: /images/favicon.png
google-analytics: null
permalink: none
baseurl: ""
