- id: askgov
  title: AskGov
  alias:
    - AskGov
  category: productivity
  image: https://file.go.gov.sg/askgovlogo.png
  sum: Q&A platform for members of the public
  link: https://products.open.gov.sg/askgov

- id: calsg
  title: CalSG
  alias:
    - CalSG
  category: productivity
  image: https://file.go.gov.sg/calsg-logo.png
  sum: Appointment bookings for Government
  link: https://products.open.gov.sg/calsg

- id: checkfirst
  title: CheckFirst
  alias:
    - CheckFirst
  category: productivity
  image: https://www.checkfirst.gov.sg/assets/logo.svg
  sum: Calculator and eligibility builder for the government
  link: https://products.open.gov.sg/checkfirst

- id: datagovsg
  title: Data.gov.sg
  alias:
    - Data.gov.sg
    - Data.gov
  category: productivity
  image: https://file.go.gov.sg/datagovsg-logo.png
  sum: Open repository for Singapore’s public data
  link: https://products.open.gov.sg/datagovsg

- id: formsg
  title: FormSG
  alias:
    - FormSG
  category: productivity
  image: https://file.go.gov.sg/formsg-logo-2.png
  sum: Build government forms in minutes
  link: https://products.open.gov.sg/formsg

- id: gogovsg
  title: GoGovSG
  alias:
    - GoGovSG
    - Go.gov.sg
    - go.gov.sg
    - Go.gov
  category: productivity
  image: https://file.go.gov.sg/gogovlogo.png
  sum: Create official government links in seconds
  link: https://products.open.gov.sg/gogovsg

- id: isomer
  title: Isomer
  alias:
    - Isomer
  category: productivity
  image: https://file.go.gov.sg/isomer-logo2.png
  sum: A static website building and hosting solution for the public service
  link: https://products.open.gov.sg/isomer

- id: pair
  title: Pair
  alias:
    - Pair
  category: productivity
  image: https://file.go.gov.sg/pair-logo.png
  sum: Large language model powered assistant for public officers
  link: https://products.open.gov.sg/pair

- id: plumber
  title: Plumber
  alias:
    - Plumber
  category: productivity
  image: https://file.go.gov.sg/plumber-logo.png
  sum: Workflow automation tool for everyday public officers
  link: https://products.open.gov.sg/plumber

- id: postman
  title: Postman
  alias:
    - Postman
  category: productivity
  image: https://file.go.gov.sg/postman-icon.png
  sum: An omnichannel communication tool for the Singapore Government
  link: https://products.open.gov.sg/postman

- id: scamshield
  title: ScamShield
  alias:
    - ScamShield
  category: anti-scam
  image: https://www.scamshield.org.sg/images/scamshield-favicon.png
  sum: Block unsolicited messages and calls
  link: https://products.open.gov.sg/scamshield

- id: sgid
  title: sgID
  alias:
    - sgID
    - SGID
  category: anti-scam
  image: https://file.go.gov.sg/sgid-key.png
  sum: Privacy-based authentication system
  link: https://products.open.gov.sg/sgid

- id: parkingsg
  title: ParkingSG
  alias:
    - Parking
    - ParkingSG
    - Parking.sg
    - Parking.SG
  category: payments
  image: https://file.go.gov.sg/parking-logo.png
  sum: Pay for parking using your mobile devices
  link:  https://products.open.gov.sg/parkingsg

- id: paysg
  title: PaySG
  alias:
    - PaySG
  category: payments
  image: https://pay.gov.sg/favicon.ico
  sum: Digitise payments for government agencies
  link: https://products.open.gov.sg/paysg

- id: redeem
  title: RedeemSG
  alias:
    - RedeemSG
    - Redeem
  category: payments
  image: https://file.go.gov.sg/redeemicon.png
  sum: Redemption tracking system to monitor the distribution of goods, tickets and vouchers in real time.
  link: https://products.open.gov.sg/redeem

- id: has
  title: HAS
  alias:
    - HAS
  category: healthcare
  image: https://file.go.gov.sg/has-logo.png
  sum: Find and book vaccine appointments near you
  link:  https://products.open.gov.sg/has

- id: care360
  title: Care360
  alias:
    - Care360
  category: healthcare
  image: https://file.go.gov.sg/care360-logo.png
  sum: Patient management system for medical social workers.
  link: https://products.open.gov.sg/care360
