- id: askgov
  name: AskGov
- id: calsg
  name: CalSG
- id: checkfirst
  name: CheckFirst
- id: datagovsg
  name: Data.gov.sg
- id: datagovsg
  name: Data.gov
- id: formsg
  name: FormSG
- id: gogovsg
  name: GoGovSG
- id: gogovsg
  name: Go.gov.sg
- id: isomer
  name: Isomer
- id: pair
  name: Pair
- id: plumber
  name: Plumber
- id: postman
  name: Postman
- id: scamshield
  name: ScamShield
- id: sgid
  name: sgID
- id: parkingsg
  name: ParkingSG
- id: parkingsg
  name: Parking.sg
- id: paysg
  name: PaySG
- id: redeem
  name: RedeemSG
- id: redeem
  name: Redeem
- id: has
  name: HAS
- id: care360
  name: Care360